# Generated by Django 2.2.7 on 2019-11-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='balance',
            new_name='number_of_product',
        ),
    ]
