# Generated by Django 2.2.7 on 2019-11-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockInBasket',
        ),
    ]
